-- CORREÇÃO DE ERRO DE TIPO (UUID)
-- Este script corrige o erro de compatibilidade entre as tabelas.
-- Copie e cole no SQL Editor do Supabase e clique em "Run".

-- 1. Adicionar colunas de fotos e vídeos na tabela de leads (caso não existam)
ALTER TABLE public.leads_veiculos 
ADD COLUMN IF NOT EXISTS fotos TEXT[],
ADD COLUMN IF NOT EXISTS videos TEXT[];

-- 2. Recriar a tabela de mensagens com o tipo correto de ID (UUID)
DROP TABLE IF EXISTS public.mensagens;

CREATE TABLE public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    lead_id UUID NOT NULL REFERENCES public.leads_veiculos(id) ON DELETE CASCADE, -- CORRIGIDO PARA UUID
    remetente TEXT NOT NULL, -- 'admin' ou 'cliente'
    conteudo TEXT NOT NULL,
    lida BOOLEAN DEFAULT false
);

-- 3. Habilitar Segurança (RLS)
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;

-- 4. Criar Políticas de Acesso (Permitir tudo para mensagens)
CREATE POLICY "Permitir acesso total a mensagens"
ON public.mensagens
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 5. Configurar Storage para Fotos e Vídeos (Bucket 'veiculos')
INSERT INTO storage.buckets (id, name, public)
VALUES ('veiculos', 'veiculos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 6. Políticas de Storage (Upload e Leitura Pública)
DROP POLICY IF EXISTS "Permitir upload público de veiculos" ON storage.objects;
DROP POLICY IF EXISTS "Permitir leitura pública de veiculos" ON storage.objects;

CREATE POLICY "Permitir upload público de veiculos"
ON storage.objects
FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'veiculos');

CREATE POLICY "Permitir leitura pública de veiculos"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'veiculos');

-- 7. Garantir permissões finais
GRANT ALL ON public.mensagens TO anon, authenticated;
GRANT ALL ON public.mensagens TO service_role;

SELECT 'Correção aplicada com sucesso! Tabela mensagens recriada com UUID.' as status;
