-- CRIAÇÃO DA TABELA DE LEADS DE VEÍCULOS
-- Copie e cole todo este conteúdo no SQL Editor do Supabase e clique em "Run"

-- 1. Cria a tabela se não existir
CREATE TABLE IF NOT EXISTS public.leads_veiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    cliente_nome TEXT NOT NULL,
    telefone TEXT NOT NULL,
    email TEXT,
    marca TEXT,
    modelo TEXT,
    ano_modelo TEXT,
    cor TEXT,
    quilometragem NUMERIC,
    placa TEXT,
    renavam TEXT,
    valor_fipe NUMERIC,
    preco_cliente NUMERIC,
    entrada NUMERIC,
    situacao_financeira TEXT,
    problemas TEXT[], -- Array de strings para listar os problemas
    status TEXT DEFAULT 'novo',
    observacoes TEXT,
    notifications_enabled BOOLEAN DEFAULT false
);

-- 2. Habilita Row Level Security (RLS)
ALTER TABLE public.leads_veiculos ENABLE ROW LEVEL SECURITY;

-- 3. Remove políticas antigas para evitar conflitos
DROP POLICY IF EXISTS "Permitir inserção pública" ON public.leads_veiculos;
DROP POLICY IF EXISTS "Permitir leitura pública" ON public.leads_veiculos;
DROP POLICY IF EXISTS "Permitir atualização pública" ON public.leads_veiculos;
DROP POLICY IF EXISTS "Anon insert" ON public.leads_veiculos;
DROP POLICY IF EXISTS "Anon read" ON public.leads_veiculos;

-- 4. Cria política para PERMITIR INSERÇÃO PÚBLICA (Essencial para o formulário funcionar)
CREATE POLICY "Permitir inserção pública"
ON public.leads_veiculos
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 5. Cria política para PERMITIR LEITURA (Para o painel administrativo ver os leads)
CREATE POLICY "Permitir leitura pública"
ON public.leads_veiculos
FOR SELECT
TO anon, authenticated
USING (true);

-- 6. Cria política para PERMITIR ATUALIZAÇÃO (Para alterar status no painel)
CREATE POLICY "Permitir atualização pública"
ON public.leads_veiculos
FOR UPDATE
TO anon, authenticated
USING (true);

-- 7. Garante permissões de sequência (para o ID automático funcionar)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 8. Garante permissões na tabela
GRANT ALL ON public.leads_veiculos TO anon, authenticated;
GRANT ALL ON public.leads_veiculos TO service_role;

-- Confirmação
SELECT 'Tabela leads_veiculos configurada com sucesso!' as status;
