-- ATUALIZAÇÃO DO BANCO DE DADOS (FOTOS, VÍDEOS E MENSAGENS)
-- Copie e cole este conteúdo no SQL Editor do Supabase e clique em "Run"

-- 1. Adicionar colunas de fotos e vídeos na tabela de leads
ALTER TABLE public.leads_veiculos 
ADD COLUMN IF NOT EXISTS fotos TEXT[],
ADD COLUMN IF NOT EXISTS videos TEXT[];

-- 2. Criar tabela de mensagens (Chat/Propostas)
CREATE TABLE IF NOT EXISTS public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    lead_id BIGINT REFERENCES public.leads_veiculos(id) ON DELETE CASCADE,
    remetente TEXT NOT NULL, -- 'admin' ou 'cliente'
    conteudo TEXT NOT NULL,
    lida BOOLEAN DEFAULT false
);

-- 3. Habilitar RLS para mensagens
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;

-- 4. Políticas para mensagens
CREATE POLICY "Permitir acesso total a mensagens"
ON public.mensagens
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 5. Configurar Storage para Fotos e Vídeos
-- Nota: A criação de buckets via SQL pode não ser suportada em todas as versões do Supabase,
-- mas as políticas sim. Se o bucket não for criado, crie manualmente no painel Storage com o nome "veiculos" e torne-o público.

INSERT INTO storage.buckets (id, name, public)
VALUES ('veiculos', 'veiculos', true)
ON CONFLICT (id) DO NOTHING;

-- 6. Políticas de Storage (Permitir upload público para 'veiculos')
CREATE POLICY "Permitir upload público de veiculos"
ON storage.objects
FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'veiculos');

CREATE POLICY "Permitir leitura pública de veiculos"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'veiculos');

-- 7. Garantir permissões
GRANT ALL ON public.mensagens TO anon, authenticated;
GRANT ALL ON public.mensagens TO service_role;

SELECT 'Banco de dados atualizado com sucesso!' as status;
